FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# despliegue con nginx

FROM nginx:alpine

COPY --from=builder ./dist/frontend /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443