FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ .
RUN echo "--- Contenido de /app/package.json ---" && cat /app/package.json && echo "--- Fin de package.json ---"
#    Esto listará todos los scripts que npm reconoce desde ese package.json.
RUN echo "--- Scripts NPM disponibles en /app ---" && npm run && echo "--- Fin de scripts NPM ---"

RUN npm run build

# despliegue con nginx

FROM nginx:alpine

COPY --from=builder /app/dist/frontend /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443